PACKAGE_NAME="ipts"
PACKAGE_VERSION="6.19.8"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_HID_IPTS=m modules"
BUILT_MODULE_NAME[0]="ipts"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
